name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y 

      - name: Install lcov
        run: sudo apt install lcov
        
      - name: Install Clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Install Scan-build  
        run: sudo apt-get install -y clang-tools

      - name: scan-build  clang-tidy
        run: mkdir build && cd build && scan-build cmake .. && scan-build make

      - name: cppcheck-action
        uses: deep5050/cppcheck-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Tests
        run: mkdir runtests && cd runtests && cmake .. && make  && make test &&  lcov -t "c_hw1" -o hw_2.info -c -d . && lcov --remove hw_2.info "/usr/include/*" "./include/*" "/usr/local/*" > coverage.info && genhtml -o report coverage.info

      - name: Valgrind install
        run: sudo apt-get update && sudo apt-get install -y valgrind && mkdir valgrind_tests  

      - name: Valgrind 
        run: cd valgrind_tests && cmake .. && make && valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s -q ./tests && valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s -q ./tests_parallel

      - name: Sanitizers address
        run: cmake -Daddress=ON .. && make && make test

      - name: Sanitizers memory
        run: cmake -Dmemory=ON .. && make && make test
        
      - name: Sanitizers undefined
        run: cmake -Dundefined=ON .. && make && make test

      - name: Sanitizers thread
        run: cmake -Dthread=ON .. && make && make test

      - name: coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: runtests/report

      

      
